import type {
  AppNotification,
  Category,
  CivicStats,
  Issue,
  Reporter,
} from './types'

/**
 * Mock data for CivicFix. This mirrors the shape a real API would return so the
 * UI can be pointed at live endpoints later with minimal changes. See
 * `lib/api.ts` for the async accessors the app actually calls.
 */

export const CATEGORIES: Category[] = [
  'Pothole',
  'Streetlight',
  'Graffiti',
  'Trash & Litter',
  'Water Leak',
  'Sidewalk',
  'Signage',
  'Other',
]

export const DEPARTMENTS = [
  'Roads & Highways',
  'Street Lighting',
  'Sanitation',
  'Water Utility',
  'Parks & Public Realm',
  'Unassigned',
]

const CURRENT_USER_ID = 'u-maya'

export const MOCK_STATS: CivicStats = {
  resolvedThisMonth: 342,
  activeReporters: 1284,
  avgResolutionDays: 4.2,
  totalOpen: 128,
}

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'CF-1042',
    title: 'Deep pothole near Elm St crosswalk',
    category: 'Pothole',
    description:
      'Large pothole roughly 40cm wide forming at the pedestrian crosswalk on Elm St. Cars are swerving to avoid it, creating a hazard for people crossing.',
    photo: '/issues/pothole.png',
    afterPhoto: null,
    status: 'in-progress',
    severity: 'High',
    upvotes: 47,
    confirmations: 12,
    reporter: 'Maya Chen',
    reporterId: CURRENT_USER_ID,
    ward: 'Ward 3 · Riverside',
    department: 'Roads & Highways',
    address: '210 Elm St, Riverside',
    lat: 40.7142,
    lng: -74.0059,
    mapX: 34,
    mapY: 42,
    distanceKm: 0.4,
    createdAt: '2026-08-06T08:14:00Z',
    updatedAt: '2026-08-11T15:30:00Z',
    slaHours: 120,
    aiConfidence: 94,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-06T08:14:00Z', note: 'Submitted with photo + GPS' },
      { stage: 'assigned', label: 'Assigned', at: '2026-08-07T09:02:00Z', note: 'Routed to Roads & Highways' },
      { stage: 'in-progress', label: 'In Progress', at: '2026-08-11T15:30:00Z', note: 'Crew scheduled for repair' },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [
      { id: 'c1', author: 'Roads & Highways', role: 'department', at: '2026-08-07T09:05:00Z', text: 'Thanks for flagging. A crew has been assigned and materials are ordered.' },
      { id: 'c2', author: 'David O.', role: 'citizen', at: '2026-08-09T18:20:00Z', text: 'Almost popped my tire here last night. Glad this is being handled.' },
      { id: 'c3', author: 'Roads & Highways', role: 'department', at: '2026-08-11T15:30:00Z', text: 'Repair crew scheduled — work begins within 48 hours.' },
    ],
  },
  {
    id: 'CF-1039',
    title: 'Streetlight out on Cedar & 4th',
    category: 'Streetlight',
    description:
      'The corner streetlight has been dark for over a week. The intersection is very dark at night and feels unsafe for people walking home.',
    photo: '/issues/streetlight.png',
    afterPhoto: null,
    status: 'assigned',
    severity: 'Medium',
    upvotes: 23,
    confirmations: 8,
    reporter: 'Priya N.',
    reporterId: 'u-priya',
    ward: 'Ward 1 · Downtown',
    department: 'Street Lighting',
    address: 'Cedar Ave & 4th St, Downtown',
    lat: 40.7195,
    lng: -74.0021,
    mapX: 58,
    mapY: 28,
    distanceKm: 1.1,
    createdAt: '2026-08-08T21:40:00Z',
    updatedAt: '2026-08-09T10:15:00Z',
    slaHours: 168,
    aiConfidence: 88,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-08T21:40:00Z' },
      { stage: 'assigned', label: 'Assigned', at: '2026-08-09T10:15:00Z', note: 'Routed to Street Lighting' },
      { stage: 'in-progress', label: 'In Progress', at: null },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [
      { id: 'c1', author: 'Street Lighting', role: 'department', at: '2026-08-09T10:16:00Z', text: 'Logged. Inspection is scheduled this week.' },
    ],
  },
  {
    id: 'CF-1021',
    title: 'Graffiti on library retaining wall',
    category: 'Graffiti',
    description:
      'Fresh spray-paint tags across the public library retaining wall facing the street. Roughly 6 meters of coverage.',
    photo: '/issues/graffiti.png',
    afterPhoto: null,
    status: 'reported',
    severity: 'Low',
    upvotes: 9,
    confirmations: 3,
    reporter: 'Sam R.',
    reporterId: 'u-sam',
    ward: 'Ward 2 · Uptown',
    department: 'Unassigned',
    address: '88 Library Ln, Uptown',
    lat: 40.7241,
    lng: -74.0102,
    mapX: 72,
    mapY: 62,
    distanceKm: 2.3,
    createdAt: '2026-08-12T13:05:00Z',
    updatedAt: '2026-08-12T13:05:00Z',
    slaHours: 240,
    aiConfidence: 91,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-12T13:05:00Z' },
      { stage: 'assigned', label: 'Assigned', at: null },
      { stage: 'in-progress', label: 'In Progress', at: null },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [],
  },
  {
    id: 'CF-1004',
    title: 'Overflowing bins at Maple Park entrance',
    category: 'Trash & Litter',
    description:
      'Trash bins at the park entrance have been overflowing for days, with bags piling up on the sidewalk. Attracting pests.',
    photo: '/issues/trash.png',
    afterPhoto: '/issues/pothole-fixed.png',
    status: 'resolved',
    severity: 'Medium',
    upvotes: 31,
    confirmations: 15,
    reporter: 'Maya Chen',
    reporterId: CURRENT_USER_ID,
    ward: 'Ward 3 · Riverside',
    department: 'Sanitation',
    address: 'Maple Park, Riverside',
    lat: 40.7108,
    lng: -74.0132,
    mapX: 22,
    mapY: 70,
    distanceKm: 0.9,
    createdAt: '2026-07-28T07:30:00Z',
    updatedAt: '2026-08-01T11:00:00Z',
    slaHours: 96,
    aiConfidence: 96,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-07-28T07:30:00Z' },
      { stage: 'assigned', label: 'Assigned', at: '2026-07-28T14:10:00Z', note: 'Routed to Sanitation' },
      { stage: 'in-progress', label: 'In Progress', at: '2026-07-30T09:00:00Z', note: 'Extra pickup scheduled' },
      { stage: 'resolved', label: 'Resolved', at: '2026-08-01T11:00:00Z', note: 'Bins cleared, pickup frequency increased' },
    ],
    comments: [
      { id: 'c1', author: 'Sanitation', role: 'department', at: '2026-07-30T09:00:00Z', text: 'Additional collection scheduled and bin capacity under review.' },
      { id: 'c2', author: 'Sanitation', role: 'department', at: '2026-08-01T11:00:00Z', text: 'Resolved — pickup frequency at this location increased to twice weekly.' },
    ],
  },
  {
    id: 'CF-0998',
    title: 'Water main leak flooding Birch Rd curb',
    category: 'Water Leak',
    description:
      'Steady stream of water flowing from under the road along the curb on Birch Rd for two days. Pooling near the storm drain.',
    photo: '/issues/water-leak.png',
    afterPhoto: null,
    status: 'in-progress',
    severity: 'High',
    upvotes: 54,
    confirmations: 21,
    reporter: 'Leo M.',
    reporterId: 'u-leo',
    ward: 'Ward 1 · Downtown',
    department: 'Water Utility',
    address: '15 Birch Rd, Downtown',
    lat: 40.7178,
    lng: -74.0075,
    mapX: 48,
    mapY: 50,
    distanceKm: 1.6,
    createdAt: '2026-08-09T06:00:00Z',
    updatedAt: '2026-08-12T08:45:00Z',
    slaHours: 48,
    aiConfidence: 97,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-09T06:00:00Z' },
      { stage: 'assigned', label: 'Assigned', at: '2026-08-09T07:30:00Z', note: 'Escalated — Water Utility' },
      { stage: 'in-progress', label: 'In Progress', at: '2026-08-10T08:00:00Z', note: 'Isolation valve located' },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [
      { id: 'c1', author: 'Water Utility', role: 'department', at: '2026-08-09T07:31:00Z', text: 'High priority — crew dispatched to assess and shut off supply.' },
    ],
  },
  {
    id: 'CF-0987',
    title: 'Cracked, uneven sidewalk trip hazard',
    category: 'Sidewalk',
    description:
      'Sidewalk slab has heaved up about 4cm creating a trip hazard right outside the bakery. Several near-falls reported.',
    photo: '/issues/pothole.png',
    afterPhoto: null,
    status: 'assigned',
    severity: 'Medium',
    upvotes: 18,
    confirmations: 6,
    reporter: 'Ana G.',
    reporterId: 'u-ana',
    ward: 'Ward 2 · Uptown',
    department: 'Roads & Highways',
    address: '5 Baker St, Uptown',
    lat: 40.7256,
    lng: -74.0044,
    mapX: 80,
    mapY: 38,
    distanceKm: 2.8,
    createdAt: '2026-08-05T16:20:00Z',
    updatedAt: '2026-08-06T09:00:00Z',
    slaHours: 168,
    aiConfidence: 82,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-05T16:20:00Z' },
      { stage: 'assigned', label: 'Assigned', at: '2026-08-06T09:00:00Z' },
      { stage: 'in-progress', label: 'In Progress', at: null },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [],
  },
  {
    id: 'CF-0975',
    title: 'Faded stop sign at school crossing',
    category: 'Signage',
    description:
      'The stop sign at the school crossing is badly faded and hard to see in low light. Important safety fix before term starts.',
    photo: '/issues/streetlight.png',
    afterPhoto: null,
    status: 'reported',
    severity: 'High',
    upvotes: 38,
    confirmations: 11,
    reporter: 'Priya N.',
    reporterId: 'u-priya',
    ward: 'Ward 4 · Eastgate',
    department: 'Unassigned',
    address: 'Oak St & School Rd, Eastgate',
    lat: 40.7301,
    lng: -73.9988,
    mapX: 64,
    mapY: 76,
    distanceKm: 3.5,
    createdAt: '2026-08-11T19:10:00Z',
    updatedAt: '2026-08-11T19:10:00Z',
    slaHours: 120,
    aiConfidence: 79,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-08-11T19:10:00Z' },
      { stage: 'assigned', label: 'Assigned', at: null },
      { stage: 'in-progress', label: 'In Progress', at: null },
      { stage: 'resolved', label: 'Resolved', at: null },
    ],
    comments: [],
  },
  {
    id: 'CF-0961',
    title: 'Graffiti cleared from underpass',
    category: 'Graffiti',
    description:
      'Extensive tagging along the pedestrian underpass walls. Reported by several commuters.',
    photo: '/issues/graffiti.png',
    afterPhoto: '/issues/pothole-fixed.png',
    status: 'resolved',
    severity: 'Low',
    upvotes: 14,
    confirmations: 7,
    reporter: 'Maya Chen',
    reporterId: CURRENT_USER_ID,
    ward: 'Ward 1 · Downtown',
    department: 'Parks & Public Realm',
    address: 'Center St Underpass, Downtown',
    lat: 40.7169,
    lng: -74.0098,
    mapX: 42,
    mapY: 18,
    distanceKm: 1.9,
    createdAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-07-27T14:00:00Z',
    slaHours: 240,
    aiConfidence: 90,
    timeline: [
      { stage: 'reported', label: 'Reported', at: '2026-07-22T10:00:00Z' },
      { stage: 'assigned', label: 'Assigned', at: '2026-07-23T09:00:00Z' },
      { stage: 'in-progress', label: 'In Progress', at: '2026-07-25T08:30:00Z' },
      { stage: 'resolved', label: 'Resolved', at: '2026-07-27T14:00:00Z', note: 'Walls cleaned and anti-graffiti coating applied' },
    ],
    comments: [
      { id: 'c1', author: 'Parks & Public Realm', role: 'department', at: '2026-07-27T14:00:00Z', text: 'Cleaned and coated to resist future tagging. Thanks for reporting!' },
    ],
  },
]

export const MOCK_REPORTERS: Reporter[] = [
  { id: 'u-leo', name: 'Leo Martins', initials: 'LM', points: 2480, tier: 'Gold', reports: 63, resolved: 51 },
  { id: 'u-priya', name: 'Priya Nair', initials: 'PN', points: 1975, tier: 'Gold', reports: 48, resolved: 39 },
  { id: CURRENT_USER_ID, name: 'Maya Chen', initials: 'MC', points: 1240, tier: 'Silver', reports: 27, resolved: 19 },
  { id: 'u-ana', name: 'Ana Gomez', initials: 'AG', points: 860, tier: 'Silver', reports: 19, resolved: 12 },
  { id: 'u-sam', name: 'Sam Reyes', initials: 'SR', points: 430, tier: 'Bronze', reports: 11, resolved: 6 },
  { id: 'u-dev', name: 'Dev Kapoor', initials: 'DK', points: 210, tier: 'Bronze', reports: 6, resolved: 3 },
]

export const CURRENT_USER = MOCK_REPORTERS.find((r) => r.id === CURRENT_USER_ID)!

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    issueId: 'CF-1042',
    title: 'Your pothole report is now In Progress',
    body: 'A repair crew has been scheduled for Elm St crosswalk.',
    at: '2026-08-11T15:30:00Z',
    phase: 'progress',
    unread: true,
  },
  {
    id: 'n2',
    issueId: 'CF-1004',
    title: 'Your report was Resolved — confirm?',
    body: 'Overflowing bins at Maple Park have been cleared. Tap to confirm the fix.',
    at: '2026-08-01T11:00:00Z',
    phase: 'resolved',
    unread: true,
  },
  {
    id: 'n3',
    issueId: 'CF-0961',
    title: 'Graffiti report resolved',
    body: 'Center St underpass was cleaned and coated. You earned +50 Civic points.',
    at: '2026-07-27T14:00:00Z',
    phase: 'resolved',
    unread: false,
  },
]

export const CURRENT_USER_LOCATION = {
  label: 'Riverside, Ward 3',
  lat: 40.7128,
  lng: -74.006,
}
